//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.0
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BricachocMvcBis.ServiceArticle {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceArticle.IServiceArticle")]
    public interface IServiceArticle {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/ChargerLesProduits", ReplyAction="http://tempuri.org/IServiceArticle/ChargerLesProduitsResponse")]
        BricachocBo.Produit[] ChargerLesProduits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/ChargerLesProduits", ReplyAction="http://tempuri.org/IServiceArticle/ChargerLesProduitsResponse")]
        System.Threading.Tasks.Task<BricachocBo.Produit[]> ChargerLesProduitsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/RechercherProduit", ReplyAction="http://tempuri.org/IServiceArticle/RechercherProduitResponse")]
        BricachocBo.Produit RechercherProduit(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/RechercherProduit", ReplyAction="http://tempuri.org/IServiceArticle/RechercherProduitResponse")]
        System.Threading.Tasks.Task<BricachocBo.Produit> RechercherProduitAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/ChargerLesFamilles", ReplyAction="http://tempuri.org/IServiceArticle/ChargerLesFamillesResponse")]
        BricachocBo.Famille[] ChargerLesFamilles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/ChargerLesFamilles", ReplyAction="http://tempuri.org/IServiceArticle/ChargerLesFamillesResponse")]
        System.Threading.Tasks.Task<BricachocBo.Famille[]> ChargerLesFamillesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/CreerProduit", ReplyAction="http://tempuri.org/IServiceArticle/CreerProduitResponse")]
        void CreerProduit(BricachocBo.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/CreerProduit", ReplyAction="http://tempuri.org/IServiceArticle/CreerProduitResponse")]
        System.Threading.Tasks.Task CreerProduitAsync(BricachocBo.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/UpdateProduit", ReplyAction="http://tempuri.org/IServiceArticle/UpdateProduitResponse")]
        void UpdateProduit(BricachocBo.Produit p);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceArticle/UpdateProduit", ReplyAction="http://tempuri.org/IServiceArticle/UpdateProduitResponse")]
        System.Threading.Tasks.Task UpdateProduitAsync(BricachocBo.Produit p);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceArticleChannel : BricachocMvcBis.ServiceArticle.IServiceArticle, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceArticleClient : System.ServiceModel.ClientBase<BricachocMvcBis.ServiceArticle.IServiceArticle>, BricachocMvcBis.ServiceArticle.IServiceArticle {
        
        public ServiceArticleClient() {
        }
        
        public ServiceArticleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceArticleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceArticleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BricachocBo.Produit[] ChargerLesProduits() {
            return base.Channel.ChargerLesProduits();
        }
        
        public System.Threading.Tasks.Task<BricachocBo.Produit[]> ChargerLesProduitsAsync() {
            return base.Channel.ChargerLesProduitsAsync();
        }
        
        public BricachocBo.Produit RechercherProduit(string id) {
            return base.Channel.RechercherProduit(id);
        }
        
        public System.Threading.Tasks.Task<BricachocBo.Produit> RechercherProduitAsync(string id) {
            return base.Channel.RechercherProduitAsync(id);
        }
        
        public BricachocBo.Famille[] ChargerLesFamilles() {
            return base.Channel.ChargerLesFamilles();
        }
        
        public System.Threading.Tasks.Task<BricachocBo.Famille[]> ChargerLesFamillesAsync() {
            return base.Channel.ChargerLesFamillesAsync();
        }
        
        public void CreerProduit(BricachocBo.Produit p) {
            base.Channel.CreerProduit(p);
        }
        
        public System.Threading.Tasks.Task CreerProduitAsync(BricachocBo.Produit p) {
            return base.Channel.CreerProduitAsync(p);
        }
        
        public void UpdateProduit(BricachocBo.Produit p) {
            base.Channel.UpdateProduit(p);
        }
        
        public System.Threading.Tasks.Task UpdateProduitAsync(BricachocBo.Produit p) {
            return base.Channel.UpdateProduitAsync(p);
        }
    }
}
